### ISSUE TITLE
Some mesh faces look transparent or disrupted.

### ISSUE THREAD

**Issue by Andrey2470T** [GreenXenith/io_scene_b3d#1]
Hi, I`ve exported a model into this format, but this look just dire. Some faces are either fully transparent or disrupted. The normals are directed properly (see the screens below).

_As in Blender 2.8_
![Screenshot_20200622_154920](https://user-images.githubusercontent.com/25750346/85289342-f61b3780-b49f-11ea-9de5-27a4def1266d.png)

_As in game_
![Screenshot_20200622_154800](https://user-images.githubusercontent.com/25750346/85289252-cbc97a00-b49f-11ea-9c44-0cb7056f2c2d.png)

However, I discovered it works properly with obj exporter.

**Comment by GreenXenith** [comment]
User error. See [this reply](https://github.com/minetest/minetest/issues/10079#issuecomment-647673615).
