### ISSUE TITLE
Add compatibility with blender 2.92

### ISSUE THREAD

**Issue by AFCMS** [GreenXenith/io_scene_b3d#2]
@GreenXenith 
Especially with linux, blender is made to be up to date. So it is very annoying to have no full compatibility with the last version of blender.

**Comment by GreenXenith** [comment]
@AFCMS Thank you for mentioning me. No one ever does that so I rarely get notifications about issues.

However, did you even try the addon? It works just fine with 2.92. If you have experienced otherwise, I am going to need some actual information on specifics.

**Comment by GreenXenith** [comment]
User confirmed no actual issue on Discord. Closing.

**Comment by poikilos** [comment]
@GreenXenith You should change your GitHub notification settings, then. You should definitely get notified of issues on your own repos (I do)!
