### ISSUE TITLE
Bugs with exporting in Blender 3.0.0.

### ISSUE THREAD

**Issue by Andrey2470T** [GreenXenith/io_scene_b3d#4]
I have found two bugs in the exporting models when using Blender 3.0.0 and they are no when using the older versions. Particularly, there's a broken compatibility between the Blender's coordinate system and Minetest's one because the exporter mismatches the coordinate axes between the first and the second, i.e. if 'X' then 'X', 'Y' then 'Y'. Here is a result of that wrong matching:

A model in Blender 3.0.0:
![Снимок экрана от 2022-01-06 01-19-46](https://user-images.githubusercontent.com/25750346/148298747-8cc7a536-60a0-423d-b8ef-db3a62596f90.png)

The same model in Minetest exported by this exporter:
![Снимок экрана от 2022-01-06 01-20-02](https://user-images.githubusercontent.com/25750346/148298805-7bf39db2-bef9-4e7e-9bdd-f583a646c5af.png)

Other bug is it exports only selected objects. Unselected ones look like in the game just transparent.

**Comment by MrRar** [comment]
Using bones in 3+ is also broken. 2.83 seems to be the latest blender that works.

**Comment by GreenXenith** [comment]
> Using bones in 3+ is also broken. 2.83 seems to be the latest blender that works.

I have successfully exported in 2.9x. Only 3.x isnt supported yet.

**Comment by MrRar** [comment]
> > Using bones in 3+ is also broken. 2.83 seems to be the latest blender that works.
> 
> I have successfully exported in 2.9x. Only 3.x isnt supported yet.

You are right. I tried 2.92.5 and it works to.
